In [1]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

print(train.shape , test.shape)
print(train.head())
print(test.head())

print(train.isnull().sum())
print(test.isnull().sum())

x_train = train.copy()
x_test = test.copy()

x_train.drop(['Email','Address','Avatar'],axis=1,inplace=True)
print(x_train.shape)

x_test.drop(['Email','Address','Avatar'],axis=1,inplace=True)
print(x_test.shape)

from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

x_train['Gender'] = label.fit_transform(x_train['Gender'])
x_test['Gender'] = label.fit_transform(x_test['Gender'])

(450, 9) (50, 9)
                               Email  \
0                 oolson@collins.com
1             campbellross@yahoo.com
2  lisagutierrez@johnson-herring.net
3          chasejennifer@hotmail.com
4            amandastanley@yahoo.com

                                             Address      Avatar  \
0    07867 Horn Lake\nWest Teresatown, VT 64387-1228        Aqua
1  6218 Michael Station Apt. 982\nSalazarburgh, N...     DarkRed
2  89300 Amber Centers Apt. 879\nVictoriaton, VT ...        Peru
3  9507 Robert Prairie Apt. 601\nEast Crystalview...  DarkOrchid
4  38528 Jerry Valleys Suite 027\nJonesstad, NY 7...   CadetBlue

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            32.533797    12.293366        37.064621              3.620365
1            34.568681    11.378087        38.304471              3.784932
2            32.407148    13.808799        37.426769              5.039955
3            33.105438    11.965020        37.277812              4.742578
4            32.096109    10.804891        37.372762              2.699562

   Gender  Yearly Amount Spent
0    Male           485.923131
1  Female           528.223809
2  Female           662.961088
3  Female           554.722084
4    Male           375.398455
                        Email  \
0  davischristina@hotmail.com
1         arice@reynolds.info
2           ppowell@gmail.com
3      pmercado@rodriguez.com
4       hunterlucas@gmail.com

                                             Address      Avatar  \
0  49352 Avila Terrace Suite 624\nAmandaland, GA ...    SeaGreen
1     740 Marshall Squares\nDavidbury, AL 94251-0846     Thistle
2    74260 Carly Mews Suite 703\nJonesberg, OR 39594  BlueViolet
3              811 Maria Run\nSanchezville, MI 04953   LightPink
4      89301 Kylie Crossroad\nPetersonberg, MH 23834   Turquoise

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.729080    11.966898        36.547596              2.957449
1            33.566474    12.235659        37.277573              2.532044
2            32.872739    12.093966        36.620774              3.049196
3            32.692392    12.296518        36.951555              1.825885
4            33.582947    12.761531        36.908190              2.479340

   Gender  Yearly Amount Spent
0  Female           506.132342
1    Male           466.421199
2    Male           471.602884
3    Male           424.185494
4    Male           478.951405
Email                   0
Address                 0
Avatar                  0
Avg. Session Length     0
Time on App             0
Time on Website         0
Length of Membership    0
Gender                  0
Yearly Amount Spent     0
dtype: int64
Email                   0
Address                 0
Avatar                  0
Avg. Session Length     0
Time on App             0
Time on Website         0
Length of Membership    0
Gender                  0
Yearly Amount Spent     0
dtype: int64
(450, 6)
(50, 6)

In [3]:
x_train.head()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Gender,Yearly Amount Spent
0,32.533797,12.293366,37.064621,3.620365,1,485.923131
1,34.568681,11.378087,38.304471,3.784932,0,528.223809
2,32.407148,13.808799,37.426769,5.039955,0,662.961088
3,33.105438,11.965020,37.277812,4.742578,0,554.722084
4,32.096109,10.804891,37.372762,2.699562,1,375.398455

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_std = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
min_scaler = MinMaxScaler()

x_train_std = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)

In [ ]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

print(train.shape , test.shape)
print(train.head())
print(test.head())

print(train.isnull().sum())
print(test.isnull().sum())

x_train = train.copy()
x_test = test.copy()

x_train.drop(['Email','Address','Avatar'],axis=1,inplace=True)
print(x_train.shape)

x_test.drop(['Email','Address','Avatar'],axis=1,inplace=True)
print(x_test.shape)

from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

x_train['Gender'] = label.fit_transform(x_train['Gender'])
x_test['Gender'] = label.fit_transform(x_test['Gender'])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

y_train = x_train['Yearly Amount Spent']
x_train = x_train.drop('Yearly Amount Spent', axis=1)

x_train = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
print(x_train.head())

y_train.reset_index(drop=True, inplace=True)

x_test = pd.DataFrame(scaler.fit_transform(x_test), columns=x_test.columns)
print(x_test.head())

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

In [ ]:
sample_predictions = pd.read_csv('test.csv')
sample_predictions['Yearly Amount Spent'] = y_pred_rf
sample_predictions = sample_predictions[['Email','Yearly Amount Spent']]
sample_predictions

In [ ]:
sample_predictions.to_csv('output.csv',index=False)